# Generated by Django 4.0 on 2023-03-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='image',
            field=models.ImageField(default=0, upload_to='tienda/images/'),
            preserve_default=False,
        ),
    ]
